import Category from '../models/Category.js';
import Provider from '../models/Provider.js';

const defaultCategories = [
  {
    key: 'house-interior',
    label: 'House Interior',
    description: 'Interior design, space planning, decor styling, and turnkey makeovers for modern living spaces.',
    image: 'https://images.unsplash.com/photo-1721322800607-8c38375eef04?auto=format&fit=crop&w=1200&q=80',
    color: 'text-blue-600',
    bg: 'bg-blue-100',
    icon: 'Home',
    trending: true,
    order: 1,
  },
  {
    key: 'gifts-customisation',
    label: 'Gifts Customisation',
    description: 'Personalized gifts, custom engravings, and handcrafted keepsakes for every occasion and brand gifting.',
    image: 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?auto=format&fit=crop&w=1200&q=80',
    color: 'text-green-600',
    bg: 'bg-green-100',
    icon: 'Gift',
    trending: false,
    order: 2,
  },
  {
    key: 'automotive',
    label: 'Automotive',
    description: 'Detailing, wraps, performance upgrades, audio, and interior customization for cars and bikes.',
    image: 'https://images.unsplash.com/photo-1489824904134-891ab64532f1?auto=format&fit=crop&w=1200&q=80',
    color: 'text-red-600',
    bg: 'bg-red-100',
    icon: 'Car',
    trending: false,
    order: 3,
  },
  {
    key: 'house-construction',
    label: 'House Construction',
    description: 'New builds, remodeling, and structural renovations with transparent project management and quality workmanship.',
    image: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1200&q=80',
    color: 'text-pink-600',
    bg: 'bg-pink-100',
    icon: 'Building',
    trending: false,
    order: 4,
  },
  {
    key: 'business-services',
    label: 'Business Services',
    description: 'Consulting, branding, marketing, and IT solutions to launch, scale, and modernize your business.',
    image: 'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?auto=format&fit=crop&w=1200&q=80',
    color: 'text-indigo-600',
    bg: 'bg-indigo-100',
    icon: 'Briefcase',
    trending: false,
    order: 5,
  },
  {
    key: 'women-wear-customisation',
    label: 'Women Wear Customisation',
    description: 'Bespoke tailoring, alterations, and custom apparel for weddings, events, and everyday fashion.',
    image: 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=1200&q=80',
    color: 'text-purple-600',
    bg: 'bg-purple-100',
    icon: 'Shirt',
    trending: false,
    order: 6,
  },
  {
    key: 'tattoo',
    label: 'Tattoo',
    description: 'Custom designs, fine-line, shading, and cover-ups by experienced, hygienic tattoo artists.',
    image: 'https://images.unsplash.com/photo-1475868530036-7e1f42b9c91c?auto=format&fit=crop&w=1200&q=80',
    color: 'text-orange-600',
    bg: 'bg-orange-100',
    icon: 'Palette',
    trending: false,
    order: 7,
  },
  {
    key: 'mens-wear-customisation',
    label: 'Mens Wear Customisation',
    description: 'Tailored suits, alterations, and custom menswear for weddings, business, and everyday style.',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=1200&q=80',
    color: 'text-teal-600',
    bg: 'bg-teal-100',
    icon: 'Users',
    trending: false,
    order: 8,
  },
  {
    key: 'art-painting',
    label: 'Art & Painting',
    description: 'Commissioned artwork, murals, canvases, and decorative painting for homes and businesses.',
    image: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&w=1200&q=80',
    color: 'text-amber-600',
    bg: 'bg-amber-100',
    icon: 'PaintBucket',
    trending: false,
    order: 9,
  },
];

export const seedInitialData = async () => {
  // Always upsert default categories so updates to seed reflect in DB
  for (const cat of defaultCategories) {
    await Category.updateOne({ key: cat.key }, { $set: cat }, { upsert: true });
  }
  await seedProviders();
};

// ------------------------------- Providers Seed ---------------------------------

const defaultProviders = [
  {
    fullName: 'Sarah Johnson',
    companyName: 'Elite Interior Design',
    category: 'house-interior',
    email: 'sarah.johnson@example.com',
    phone: '+911100000001',
    licenseNumber: 'LIC-HI-00001',
    address: { city: 'Mumbai', state: 'Maharashtra', country: 'IN' },
    profilePicture: 'https://images.unsplash.com/photo-1721322800607-8c38375eef04?auto=format&fit=crop&w=600&q=80',
    status: 'active',
    rating: 4.9,
    totalReviews: 127,
  },
  {
    fullName: 'Rajesh Kumar',
    companyName: 'AutoCraft Modifications',
    category: 'automotive',
    email: 'rajesh.kumar@example.com',
    phone: '+911100000002',
    licenseNumber: 'LIC-AU-00002',
    address: { city: 'Delhi', state: 'NCR', country: 'IN' },
    profilePicture: 'https://images.unsplash.com/photo-1489824904134-891ab64532f1?auto=format&fit=crop&w=600&q=80',
    status: 'active',
    rating: 4.8,
    totalReviews: 89,
  },
  {
    fullName: 'Priya Sharma',
    companyName: 'Personalized Gifts Co.',
    category: 'gifts-customisation',
    email: 'priya.sharma@example.com',
    phone: '+911100000003',
    licenseNumber: 'LIC-GI-00003',
    address: { city: 'Bangalore', state: 'Karnataka', country: 'IN' },
    profilePicture: 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?auto=format&fit=crop&w=600&q=80',
    status: 'active',
    rating: 4.7,
    totalReviews: 156,
  },
  {
    fullName: 'Meera Patel',
    companyName: 'Fashion Forward',
    category: 'women-wear-customisation',
    email: 'meera.patel@example.com',
    phone: '+911100000004',
    licenseNumber: 'LIC-WW-00004',
    address: { city: 'Ahmedabad', state: 'Gujarat', country: 'IN' },
    profilePicture: 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=600&q=80',
    status: 'active',
    rating: 4.9,
    totalReviews: 203,
  },
  {
    fullName: 'Vikram Singh',
    companyName: 'BuildCraft Construction',
    category: 'house-construction',
    email: 'vikram.singh@example.com',
    phone: '+911100000005',
    licenseNumber: 'LIC-HC-00005',
    address: { city: 'Pune', state: 'Maharashtra', country: 'IN' },
    profilePicture: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=600&q=80',
    status: 'active',
    rating: 4.6,
    totalReviews: 78,
  },
  {
    fullName: 'Anita Reddy',
    companyName: 'TechSolutions Pro',
    category: 'business-services',
    email: 'anita.reddy@example.com',
    phone: '+911100000006',
    licenseNumber: 'LIC-BS-00006',
    address: { city: 'Hyderabad', state: 'Telangana', country: 'IN' },
    profilePicture: 'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?auto=format&fit=crop&w=600&q=80',
    status: 'active',
    rating: 4.8,
    totalReviews: 134,
  },
  {
    fullName: 'Rohit Gupta',
    companyName: 'Modern Spaces',
    category: 'house-interior',
    email: 'rohit.gupta@example.com',
    phone: '+911100000007',
    licenseNumber: 'LIC-HI-00007',
    address: { city: 'Chennai', state: 'Tamil Nadu', country: 'IN' },
    profilePicture: 'https://images.unsplash.com/photo-1721322800607-8c38375eef04?auto=format&fit=crop&w=600&q=80',
    status: 'active',
    rating: 4.7,
    totalReviews: 91,
  },
  {
    fullName: 'Kavya Nair',
    companyName: 'Artisan Gifts',
    category: 'gifts-customisation',
    email: 'kavya.nair@example.com',
    phone: '+911100000008',
    licenseNumber: 'LIC-GI-00008',
    address: { city: 'Kochi', state: 'Kerala', country: 'IN' },
    profilePicture: 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?auto=format&fit=crop&w=600&q=80',
    status: 'active',
    rating: 4.9,
    totalReviews: 167,
  },
  {
    fullName: 'Arjun Mishra',
    companyName: 'Canvas & Brush Studio',
    category: 'art-painting',
    email: 'arjun.mishra@example.com',
    phone: '+911100000009',
    licenseNumber: 'LIC-AP-00009',
    address: { city: 'Jaipur', state: 'Rajasthan', country: 'IN' },
    profilePicture: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&w=600&q=80',
    status: 'active',
    rating: 4.8,
    totalReviews: 92,
  }
];

const seedProviders = async () => {
  for (const p of defaultProviders) {
    await Provider.updateOne(
      { $or: [{ email: p.email }, { licenseNumber: p.licenseNumber }] },
      { $set: p },
      { upsert: true }
    );
  }
};